project:
  type: website
  output-dir: docs

website:
  title: "Antonio Elías"
  description: "Researcher and Professor of Statistics."
  page-navigation: true
  navbar:
    logo: static/img/logo.png
    right:
      - href: about/index.qmd
        text: about me |
      - href: research/index.qmd
        text: research |
      - href: teaching/index.qmd
        text: teaching |

  page-footer:  
    left: >-
     &#169; 2024 Antonio Elías &#8729; Made with [Quarto](https://quarto.org)
    #center: |
    #  <a class="link-dark me-1" href="https://github.com/aefdz" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
    #  <a class="link-dark me-1" href="https://www.linkedin.com/in/antonio-el%C3%ADas-fern%C3%A1ndez-656ab495/" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
    #  <a class="link-dark me-1" href="https://orcid.org/0000-0002-3078-549X" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
    #  <a class="link-dark me-1" href="https://scholar.google.es/citations?user=nx1VBZEAAAAJ&hl=es" title="Google Scholar" target="_blank"rel="noopener">{{< ai google-scholar >}}</a>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

